name: Run unit tests
on: [pull_request_target]
jobs:
  run-unit-tests:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: Develop

      - name: Change wrapper permissions
        run: chmod +x gradlew

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest